version: '3.8'
services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: some_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  app:
    build:
      context: ./knowledge-sharing
      dockerfile: Dockerfile
    environment:
      JASYPT_ENCRYPTOR_PASSWORD: ${JASYPT_ENCRYPTOR_PASSWORD}
    ports:
      - "8080:8080"  # 여기서 "8080:8080"은 Docker 컨테이너의 8080 포트를 호스트의 8080 포트에 바인딩합니다. 필요에 따라 변경하세요.
    depends_on:
      - mysql
      - redis

volumes:
  mysql-data:
  redis-data: