server:
  port: 4040

spring:
  profiles:
    active: db, jwt, mail, s3 ,oauth
  datasource:
    driver-class-name: ${driver-class-name}
    url: ${url}
    username: ${username_}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: ${host}
    port: ${port}
    username: ${mail-name}
    password: ${mail-pw}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao-client-id}
            client-secret: ${kakao-client-secret}

            redirect-uri: '{baseUrl}/oauth2/callback/{registrationId}'
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_image
              - profile_nickname
              - account_email
          naver:
            client-id: ${naver-client-id}
            client-secret: ${naver-client-secret}

            redirect-uri: '{baseUrl}/oauth2/callback/{registrationId}'
            authorization-grant-type: authorization_code
            scope:
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  data:
    redis:
      host: localhost
      port: 6379



cloud:
  aws:
    credentials:
      access-key: ${accessKey}
      secret-key: ${secretKey}
    s3:
      bucket: ${bucketName}
    region:
      static: ap-northeast-2
    stack:
      auto: false


