server:
  port: 4040
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(NNagm7HUOgOAm5JKunXE0mGUkoAcvQITc5ZnS+sKvyBEj/pMga2Dy58A57mIipv79TmBlrTwcVBI3kLi31CO1ps04Z5ALmuw83/2Rs8wS7RfSfkroFXqMY7Ty65IvGpf4OYNZqvU0eo=)
    username: ENC(sAxGMaGwANmdGhzv1z0Syg==)
    password: ENC(LOjsqwSFgoVgARXo4KVMpLRWXzSETUEi)


  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(7PuKKOb0jSMJUxBZY/Alsj8Rm1QaTfTfbGQU1jglJHw=)
    password: ENC(6zWY/jW56r7nJmnvAlwqkGW/z12xIV5VxMoYrF8g57A=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(lN/Xa0LYwIKYD36v3rXP+93ehShimctF7t/xJMbYXTHADd1VY2HvK86SoHVfhYSx)
            client-secret: ENC(9CJ51wZRFl7YrevWFuQPc329oqcBsjo6SRtPWAEBNpqOLER/syKrHrhLcSVygYGK)

            redirect-uri: '{baseUrl}/oauth2/callback/{registrationId}'
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_image
              - profile_nickname
              - account_email
          naver:
            client-id: ENC(obUIqzVRKabOVJGtYW12SrYHwBnwrftM/K4lTtjzaPo=)
            client-secret: ENC(aMn1+v9uHBUNAiatXGD0hasgdYceG1A8)

            redirect-uri: '{baseUrl}/oauth2/callback/{registrationId}'
            authorization-grant-type: authorization_code
            scope:
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  data:
    redis:
      host: localhost
      port: 6379


cloud:
  aws:
    credentials:
      access-key: ENC(N03M2no7K9/xvFNvYkHwAU1uiN2IboQ8V5spR8hKRp0=)
      secret-key: ENC(yO9t9VD3wr5PUnSNCttQqMqvIRRXGuw1ZKiT/NkguznZc2MptT+nMr/oX0//cg0/RroQvZRCFyw=)
    s3:
      bucket: ENC(mQStqKUDxgmmeoSr9vrVAnQ3HG+pWhlxZk7BrtWfpIk=)
    region:
      static: ap-northeast-2
    stack:
      auto: false
logging:
  level:
    org:
      springframework:
        security:
          DEBUG

secret-key: ENC(3FGPF5Z13b5WvsumK+tx/A1XtAc9P/BqFro29ldlQKwgBex4X3qBuUlTkDvALTlXHUT+wP1N3sQ3LDukRzZOVSNJUwzMAaXoJDjhIrnvh49ui3f0Kz8R0BJ2viSnE506)

